pipeline {
    agent any
    
    stages{
        stage('listing_scripts'){
            steps {
                sh '''
                  echo "Listing scripts from Github repo"

                  ls ${WORKSPACE}/

                  '''
            }
        }
        
         stage('executing_scripts'){
            steps {
                sh '''
                
                  echo Build is sucessful on stage2
                  bash  ${WORKSPACE}/linux/script.sh
                  '''
            }
        }
    }
}
